# Partie 1 Basics backen API
# TODO: Choose a java JRE
# TODO:  Add the compiled java (aka bytecode, aka .class)
# TODO: Run the Java with: “java Main” command.
#FROM eclipse-temurin:21-jre-alpine
#COPY Main.class .
#CMD ["java","Main"]

# Build stage
FROM eclipse-temurin:21-jdk-alpine AS myapp-build
ENV MYAPP_HOME=/opt/myapp
WORKDIR $MYAPP_HOME

RUN apk add --no-cache maven

COPY pom.xml .
COPY src ./src
RUN mvn package -DskipTests

# Run stage
FROM eclipse-temurin:21-jre-alpine
ENV MYAPP_HOME=/opt/myapp
WORKDIR $MYAPP_HOME
COPY --from=myapp-build $MYAPP_HOME/target/*.jar $MYAPP_HOME/myapp.jar

ENTRYPOINT ["java", "-jar", "myapp.jar"]
